core_annotation:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:     /login
    defaults:
        _controller: "CoreBundle:Security:login"

login_check:
    path: /login_check

logout:
    path: /logout

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin