<?php

namespace CoreBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{
    public function countGroupesOnTheme($id)
    {
        $qb = $this
            ->createQueryBuilder('g')
            ->select('COUNT(g)')
            ->join('g.theme', 't')
            ->where('t.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getSingleScalarResult();
    }
}
