<?php

namespace CoreBundle\Repository;

/**
 * PackActivitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackActivitesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllWithActivites()
    {
        $qb = $this
            ->createQueryBuilder('p')
            ->join('p.activites', 'a');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
